### ISSUE TITLE
Is it possible to swap the crystal for a resonator?

### ISSUE THREAD

**Issue by andrewsleigh** [satshas/satshakit#2]
Hi Daniele, I'm trying to make a modified version of this board, mostly just with different headers to make programming easier. But I was also thinking of swapping out the crystal (and capacitors) for a resonator. Is there any reason why you used this as the clock source over a resonator? Would a resonator still keep the same level of Arduino compatibility? (I really like this aspect.)

**Comment by satshas** [comment]
Hi Andrew,

first of all refer to the following repository: https://github.com/satshakit/satshakit

This is one is outdated as you can read at the beginning of the README.

You can certainly swap the crystal for a resonator, the reason why I am using a crystal is about the precision of the clock. 

Crystals are more accurate and stable in higher ranges of temperatures than resonator. Accurate clock means less problems/more stability in communication protocols, usage of software requiring precise frequencies,  readings and so on.  Also this is helpful in our environment where our boards are made with the CNC and soldered by hand, and where our project are prototypes, therefore requiring a stable and reliable electronics to count on.

The original objective of the satshakit was to be a flight controller of my drone, thus the usage of the crystal.

If your board does not have such mission critical purpose, and you are ok with lowering the clock stability then that's ok.

Daniele
